/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesDashboardRouteImport } from './routes/sales.dashboard'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDashboardRoute = SalesDashboardRouteImport.update({
  id: '/sales/dashboard',
  path: '/sales/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/sales/dashboard': typeof SalesDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/sales/dashboard': typeof SalesDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/sales/dashboard': typeof SalesDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/owner/dashboard' | '/sales/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/owner/dashboard' | '/sales/dashboard'
  id: '__root__' | '/' | '/login' | '/owner/dashboard' | '/sales/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  SalesDashboardRoute: typeof SalesDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/dashboard': {
      id: '/sales/dashboard'
      path: '/sales/dashboard'
      fullPath: '/sales/dashboard'
      preLoaderRoute: typeof SalesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  SalesDashboardRoute: SalesDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
